### ISSUE TITLE
would you like to merge with kotlin-logging?

### ISSUE THREAD

**Issue by oshai** [nfrankel/slf4k#1]
I saw you created this repo and thought you might want to "join-forces" and work on my similar repo: https://github.com/MicroUtils/kotlin-logging
you are also welcome to discuss it in slack: https://kotlinlang.slack.com/messages/kotlin-logging

**Comment by nfrankel** [comment]
I've checked your repo:
1. Gradle is used. This is a no-go for me.
2. Images that are used for the README are put in the `src/main/resources` folder... They will be part of the package for no real reason.
3. Creating a class for logging is overkill: it might be an option, not the only way.

For all those reasons, I have to decline.

**Comment by oshai** [comment]
thanks, this is your decision of course.
regarding your points:
1. out of curiosity, what is wrong with gradle? I don't mind to change that.
2. thanks I will fix that.
3. we can add that as well. the only drawback is giving users too many
options might cause confusion but it can be added.
thanks again for the input,
ohad.

**Comment by sschuberth** [comment]
FWIW, I just switched from kotlin-logging to slf4k as [kotlin-logging does not seem to allow me to set the log level when using logback](https://github.com/MicroUtils/kotlin-logging/issues/20#issuecomment-314391165).
