### ISSUE TITLE
Please link the Bintray artifacts to JCenter

### ISSUE THREAD

**Issue by sschuberth** [nfrankel/slf4k#3]
See [Including your Package in JCenter](https://bintray.com/docs/usermanual/uploads/uploads_centralrepositories.html#_including_your_package_in_jcenter).

**Comment by nfrankel** [comment]
Request sent

**Comment by nfrankel** [comment]
Request approved: <https://bintray.com/bintray/jcenter?filterByPkgName=slf4k>
